# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

params:
  schema:
    lintFormatCommand:
      name: "Lint Format Command"
      description: "Custom command to run for linting and formatting"
      type: string
      default: "npm run lint || true && npm run format"

nodes:
  - id: transform-and-update
    name: Transform code and update dependencies
    type: automatic
    steps:
      - id: scan-and-fix
        name: "Scan typescript files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: tsx
          semantic_analysis: file
          includes:
            - "**/*.ts"
            - "**/*.tsx"
          excludes:
            - "**/node_modules/**"
            - "**/.yarn/**"
            - "**/.yarn/releases/**"
            - "**/.yarn/releases/*.cjs"
            - "**/dist/**"
            - "**/build/**"
            - "**/.git/**"
            - "**/coverage/**"
            - "**/.next/**"
            - "**/.turbo/**"
            - "**/*.cjs"
            - "**/*.mjs"
            - "**/*.js"
            - "**/*.jsx"
            - "**/.yarn/**/*"

      - id: install-package-if-needed
        name: "Install the package and update the relevant package.json and lock file as needed"
        depends_on: 
          - scan-and-fix
        run: |
          SCRIPT=$(find . .. ../.. -name "add-dependency.sh" -path "*/regexp-to-arkregex/scripts/*" 2>/dev/null | head -1) || \
            SCRIPT=$(find . -path "*/node_modules/*/regexp-to-arkregex/scripts/add-dependency.sh" 2>/dev/null | head -1)
          [ -f "$SCRIPT" ] || { echo "Error: add-dependency.sh not found" >&2; exit 1; }
          [ -x "$SCRIPT" ] || chmod +x "$SCRIPT"
          "$SCRIPT" "${PWD}"

      - id: lint-and-format
        name: "Run linting and formatting"
        depends_on: [install-package-if-needed]
        run: |
          set -eu
          
          # Use parameter if provided, otherwise use default
          LINT_FORMAT_CMD="${PARAM_LINT_FORMAT_COMMAND:-npm run lint || true && npm run format}"
          
          echo "Running linting and formatting..."
          eval "$LINT_FORMAT_CMD"