# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: transform-and-update
    name: Transform code and update dependencies
    type: automatic
    steps:
      - id: scan-and-fix
        name: "Scan typescript files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: tsx
          includes:
            - "**/*.ts"
            - "**/*.tsx"

      - id: update-package-json-if-needed
        name: "Update the relevant package.json if needed and also sort dependencies"
        js-ast-grep:
          js_file: scripts/add-dependency.ts
          language: json
          includes:
            - "**/package.json"
