# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: transform-and-update
    name: Transform code and update dependencies
    type: automatic
    steps:
      - id: scan-and-fix
        name: "Scan typescript files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: tsx
          includes:
            - "**/*.ts"
            - "**/*.tsx"

      - id: install-package-if-needed
        name: "Install the package and update the relevant package.json and lock file as needed"
        run: |
          # Find the script by searching for it
          SCRIPT_PATH=""
          
          # Strategy 1: Try relative path (in case codemod CLI resolves it like js-ast-grep does)
          if [ -f "scripts/add-dependency.sh" ]; then
            SCRIPT_PATH="scripts/add-dependency.sh"
          # Strategy 2: Search upward from current directory for workflow.yaml
          else
            SEARCH_DIR="$PWD"
            while [ "$SEARCH_DIR" != "/" ] && [ -n "$SEARCH_DIR" ]; do
              if [ -f "$SEARCH_DIR/workflow.yaml" ] && [ -f "$SEARCH_DIR/scripts/add-dependency.sh" ]; then
                SCRIPT_PATH="$SEARCH_DIR/scripts/add-dependency.sh"
                break
              fi
              PARENT=$(dirname "$SEARCH_DIR")
              # Avoid infinite loop
              if [ "$PARENT" = "$SEARCH_DIR" ]; then
                break
              fi
              SEARCH_DIR="$PARENT"
            done
          fi
          
          # Strategy 3: Search in sibling directories (for cases where codemod and target are siblings)
          if [ -z "$SCRIPT_PATH" ]; then
            CURRENT_PARENT=$(dirname "$PWD")
            if [ -n "$CURRENT_PARENT" ] && [ "$CURRENT_PARENT" != "/" ] && [ "$CURRENT_PARENT" != "$PWD" ]; then
              # Look for module-replacement-codemods or regexp-to-arkregex in parent or sibling locations
              for possible_path in \
                "$CURRENT_PARENT/module-replacement-codemods/codemods/regexp-to-arkregex/scripts/add-dependency.sh" \
                "$CURRENT_PARENT/codemods/regexp-to-arkregex/scripts/add-dependency.sh" \
                "$CURRENT_PARENT/regexp-to-arkregex/scripts/add-dependency.sh"; do
                if [ -f "$possible_path" ]; then
                  SCRIPT_PATH="$possible_path"
                  break
                fi
              done
            fi
          fi
          
          # Strategy 4: Use find to locate the script (search from a common parent, limited scope)
          if [ -z "$SCRIPT_PATH" ] && [ -n "${HOME:-}" ]; then
            # Search in Documents/Playground or similar common development locations
            for search_root in \
              "$(dirname "$(dirname "$PWD")" 2>/dev/null)" \
              "$HOME/Documents" \
              "$HOME/Projects" \
              "$HOME"; do
              if [ -n "$search_root" ] && [ -d "$search_root" ]; then
                FOUND=$(find "$search_root" -maxdepth 6 -name "add-dependency.sh" -path "*/regexp-to-arkregex/scripts/add-dependency.sh" 2>/dev/null | head -1)
                if [ -n "$FOUND" ] && [ -f "$FOUND" ]; then
                  SCRIPT_PATH="$FOUND"
                  break
                fi
              fi
            done
          fi
          
          if [ -n "$SCRIPT_PATH" ] && [ -f "$SCRIPT_PATH" ]; then
            # Use absolute path to avoid issues
            if [ "${SCRIPT_PATH#/}" = "$SCRIPT_PATH" ]; then
              # Relative path, make it absolute
              SCRIPT_PATH="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/$(basename "$SCRIPT_PATH")"
            fi
            bash "$SCRIPT_PATH" "$PWD"
          else
            echo "Error: Could not find scripts/add-dependency.sh" >&2
            echo "Current directory: $PWD" >&2
            echo "Searched:" >&2
            echo "  1. scripts/add-dependency.sh (relative)" >&2
            echo "  2. Upward from current directory for workflow.yaml" >&2
            echo "  3. Sibling directories" >&2
            echo "  4. Common development directories" >&2
            exit 1
          fi