# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: transform-and-update
    name: Transform code and update dependencies
    type: automatic
    steps:
      - id: scan-and-fix
        name: "Scan typescript files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: tsx
          includes:
            - "**/*.ts"
            - "**/*.tsx"

      - id: install-package-if-needed
        name: "Install the package and update the relevant package.json and lock file as needed"
        run: bash scripts/add-dependency.sh "${PWD}"